# Generated by Django 4.0.3 on 2022-04-04 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clone', '0003_profile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='likes',
            field=models.ManyToManyField(default=0, related_name='posts', to='clone.profile'),
        ),
    ]
