# Generated by Django 4.0.3 on 2022-04-04 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clone', '0004_alter_image_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='likes',
            field=models.ManyToManyField(blank=True, default=0, related_name='lkes', to='clone.profile'),
        ),
    ]
